"""add_operators_workscope_import_conditions_history

Revision ID: 0304b25ca69e
Revises: a1b2c3d4e5f6
Create Date: 2026-03-23 13:47:52.057702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0304b25ca69e'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_name'), 'operators', ['name'], unique=True)
    op.create_table('condition_answer_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('condition_token', sa.String(length=128), nullable=False),
    sa.Column('old_answer', sa.String(length=16), nullable=True),
    sa.Column('new_answer', sa.String(length=16), nullable=False),
    sa.Column('changed_by', sa.String(length=128), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_answer_history_project_id'), 'condition_answer_history', ['project_id'], unique=False)
    op.create_table('workscope_import_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('task_ref', sa.String(length=256), nullable=True),
    sa.Column('mpd_ref', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('zone', sa.String(length=256), nullable=True),
    sa.Column('section', sa.String(length=128), nullable=True),
    sa.Column('mh', sa.String(length=64), nullable=True),
    sa.Column('cost', sa.String(length=64), nullable=True),
    sa.Column('extra_raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workscope_import_rows_mpd_ref'), 'workscope_import_rows', ['mpd_ref'], unique=False)
    op.create_index(op.f('ix_workscope_import_rows_project_id'), 'workscope_import_rows', ['project_id'], unique=False)
    op.create_index(op.f('ix_workscope_import_rows_task_ref'), 'workscope_import_rows', ['task_ref'], unique=False)
    op.drop_index(op.f('ix_aviation_document_tasks_line_number'), table_name='aviation_document_tasks')
    op.add_column('project_condition_answers', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('projects', sa.Column('operator_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_operator_id'), 'projects', ['operator_id'], unique=False)
    # SQLite does not support adding FK constraints via ALTER; the column is already nullable
    # and the relationship is enforced at the application level.
    # op.create_foreign_key(None, 'projects', 'operators', ['operator_id'], ['id'])
    # ### end Alembic commands ###

    # ── Seed default operators (alphabetical) ───────────────────────────────
    from datetime import datetime as _dt
    operators_table = sa.table('operators', sa.column('name', sa.String), sa.column('created_at', sa.DateTime))
    _now = _dt.utcnow()
    _names = sorted([
        "Aegean Airlines", "Aer Lingus", "Aero Dili", "Aerolineas Argentinas",
        "AeroMexico", "Air Arabia Abu Dhabi LLC", "Air Arabia PJSC", "Air Astana",
        "Air Cairo", "Air Canada", "Air Europa", "Air Guilin",
        "Air India Express", "Air India Limited", "Air KBZ", "Air Mauritius",
        "Air Moana", "Air Niugini", "Air Nostrum", "Air Serbia",
        "Air Sial", "Air Transat", "AirBlue", "AirSwift",
        "AJet Hava Tasimaciligi A.S. (d.b.a. Ajet)", "Albastar",
        "Alliance Air", "American Airlines", "Arajet", "Aruba Airlines",
        "ASKY Airlines", "Asiana Airlines", "Aviair PTY LTD", "Avianca",
        "Avion Express", "Azul", "BBN Airlines", "BBN Airlines Indonesia",
        "Bolivian Aviation (BOA)", "Braathens Regional Airlines", "Brussels Airlines SA",
        "Canary Fly S.L.", "Caribbean Airlines", "Cebgo Inc", "Central Airlines",
        "China Airlines", "China United Airlines", "Citilink Indonesia",
        "Clic Air", "Corendon Airlines", "COPA Airlines",
        "Delta Airlines", "Deutsche Lufthansa AG", "EasyJet Switzerland",
        "easyJet", "easyJet Europe", "Eastar Jet", "Egyptair",
        "Emerald Airlines", "Emirates", "Ethiopian Airlines",
        "Fiji Airways", "Finnair", "Flyadeal",
        "FlyArystan Joint Stock Company", "Fly91",
        "Garuda Indonesia", "Global Crossing Airlines", "GOL Linhas Aereas",
        "Guangxi Beibu Gulf Airlines", "Gulf Air",
        "Hainan Airlines", "Hawaiian Airlines", "Hi Fly",
        "Hong Kong Airlines", "Hong Kong Express Airways Limited",
        "Iberia", "Icelandair", "In Storage", "In Storage / Total Loss (Russia)",
        "Indigo Airlines", "Jazeera Airways", "Jambojet Limited",
        "JETTIME A/S", "Jetstar Japan", "JetBlue Airways",
        "Kalitta Air", "Kenya Airways", "KLM",
        "Korean Airlines", "LAN Airlines",
        "LATAM Airlines Group S.A.", "Loganair",
        "Loftleidir Icelandic EHF", "Manta Air",
        "Mel Air Limited", "MIAT Mongolian Airlines",
        "Myanmar Airways International Company Limited", "Myanmar National Airlines",
        "Norwegian", "Norwegian Air Sweden", "Nouvelair Tunisie",
        "Naysa Servicios Aereos S.L.", "Nyx OU",
        "Olympic Air S.A.", "Oman Air",
        "Peach", "Pegasus", "Philippine Airlines",
        "PNG Air", "PT Batik Air Indonesia", "PT Lion Mentari Air",
        "Royal Air Maroc", "Royal Jordanian Airlines",
        "SAS", "Satena", "Shandong Airlines",
        "Sky Airlines", "Skymark Airlines", "Smartwings a.s",
        "Southwest Airlines", "Spirit Airlines", "Spring Airlines",
        "Starflyer Inc.", "SunExpress Airlines", "Super Air Jet",
        "t'Way Airlines", "TAAG Angola Airlines", "TAP-Air Portugal",
        "Tarco Aviation", "TAROM", "Thai AirAsia",
        "Thai AirAsia X Company Ltd.", "Thai Airways International",
        "Thai Vietjet Air Joint Stock", "Toki Air",
        "Transavia Airlines", "Transavia France",
        "Trigana Air Service", "TUI Travel Aviation Finance Limited",
        "TUIfly", "Turkish airlines",
        "United Airlines", "US-Bangla Airlines",
        "Uzbekistan Airways", "Uzbekistan Helicopters LLC",
        "Vietjet", "Vietnam Airlines", "Virgin Australia",
        "vivaaerobus", "Vueling Airlines",
        "West Air Company Limited", "Westjet",
        "Windrose Airlines", "Wizz Air", "Xiamen Airlines",
    ])
    op.bulk_insert(operators_table, [{"name": n, "created_at": _now} for n in _names])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_operator_id'), table_name='projects')
    op.drop_column('projects', 'operator_id')
    op.drop_column('project_condition_answers', 'updated_at')
    op.create_index(op.f('ix_aviation_document_tasks_line_number'), 'aviation_document_tasks', ['line_number'], unique=False)
    op.drop_index(op.f('ix_workscope_import_rows_task_ref'), table_name='workscope_import_rows')
    op.drop_index(op.f('ix_workscope_import_rows_project_id'), table_name='workscope_import_rows')
    op.drop_index(op.f('ix_workscope_import_rows_mpd_ref'), table_name='workscope_import_rows')
    op.drop_table('workscope_import_rows')
    op.drop_index(op.f('ix_condition_answer_history_project_id'), table_name='condition_answer_history')
    op.drop_table('condition_answer_history')
    op.drop_index(op.f('ix_operators_name'), table_name='operators')
    op.drop_table('operators')
    # ### end Alembic commands ###
