"""initial_schema

Revision ID: 2c6ae3cbcd42
Revises: 
Create Date: 2026-03-13 14:02:19.598313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6ae3cbcd42'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('sanitized_payload_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mpd_datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('parsed_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpd_datasets_manufacturer'), 'mpd_datasets', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_mpd_datasets_model'), 'mpd_datasets', ['model'], unique=False)
    op.create_index(op.f('ix_mpd_datasets_revision'), 'mpd_datasets', ['revision'], unique=False)
    op.create_table('mpd_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('task_reference', sa.String(length=256), nullable=True),
    sa.Column('task_number', sa.String(length=128), nullable=True),
    sa.Column('task_code', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=128), nullable=True),
    sa.Column('chapter', sa.String(length=128), nullable=True),
    sa.Column('threshold_raw', sa.String(length=256), nullable=True),
    sa.Column('interval_raw', sa.String(length=256), nullable=True),
    sa.Column('threshold_normalized', sa.String(length=256), nullable=True),
    sa.Column('interval_normalized', sa.String(length=256), nullable=True),
    sa.Column('interval_json', sa.JSON(), nullable=True),
    sa.Column('source_references', sa.String(length=512), nullable=True),
    sa.Column('applicability_raw', sa.Text(), nullable=True),
    sa.Column('applicability_tokens_normalized', sa.Text(), nullable=True),
    sa.Column('job_procedure', sa.String(length=512), nullable=True),
    sa.Column('mp_reference', sa.String(length=256), nullable=True),
    sa.Column('cmm_reference', sa.String(length=256), nullable=True),
    sa.Column('zones', sa.String(length=512), nullable=True),
    sa.Column('zone_mh', sa.String(length=64), nullable=True),
    sa.Column('man', sa.String(length=64), nullable=True),
    sa.Column('access_items', sa.String(length=512), nullable=True),
    sa.Column('access_mh', sa.String(length=64), nullable=True),
    sa.Column('preparation_description', sa.Text(), nullable=True),
    sa.Column('preparation_mh', sa.String(length=64), nullable=True),
    sa.Column('skill', sa.String(length=128), nullable=True),
    sa.Column('equipment', sa.String(length=512), nullable=True),
    sa.Column('extra_raw', sa.JSON(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['mpd_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpd_tasks_dataset_id'), 'mpd_tasks', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_mpd_tasks_task_code'), 'mpd_tasks', ['task_code'], unique=False)
    op.create_index(op.f('ix_mpd_tasks_task_number'), 'mpd_tasks', ['task_number'], unique=False)
    op.create_index(op.f('ix_mpd_tasks_task_reference'), 'mpd_tasks', ['task_reference'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('mpd_dataset_id', sa.Integer(), nullable=True),
    sa.Column('msn', sa.String(length=64), nullable=False),
    sa.Column('tsn', sa.String(length=64), nullable=True),
    sa.Column('csn', sa.String(length=64), nullable=True),
    sa.Column('registration', sa.String(length=32), nullable=True),
    sa.Column('selected_checks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mpd_dataset_id'], ['mpd_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_mpd_dataset_id'), 'projects', ['mpd_dataset_id'], unique=False)
    op.create_index(op.f('ix_projects_msn'), 'projects', ['msn'], unique=False)
    op.create_table('modification_evidence_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('extracted_conditions', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modification_evidence_files_project_id'), 'modification_evidence_files', ['project_id'], unique=False)
    op.create_table('project_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('check_code', sa.String(length=64), nullable=False),
    sa.Column('check_name', sa.String(length=256), nullable=True),
    sa.Column('last_done_date', sa.String(length=32), nullable=True),
    sa.Column('last_done_fh', sa.String(length=32), nullable=True),
    sa.Column('last_done_fc', sa.String(length=32), nullable=True),
    sa.Column('next_due_date', sa.String(length=32), nullable=True),
    sa.Column('next_due_fh', sa.String(length=32), nullable=True),
    sa.Column('next_due_fc', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_checks_project_id'), 'project_checks', ['project_id'], unique=False)
    op.create_table('project_condition_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('condition_token', sa.String(length=128), nullable=False),
    sa.Column('answer', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_condition_answers_project_id'), 'project_condition_answers', ['project_id'], unique=False)
    op.create_table('project_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('sheet_index', sa.Integer(), nullable=True),
    sa.Column('parsed_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_files_project_id'), 'project_files', ['project_id'], unique=False)
    op.create_table('project_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_reports_project_id'), 'project_reports', ['project_id'], unique=False)
    op.create_table('applicability_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('raw_expression', sa.Text(), nullable=True),
    sa.Column('resolved', sa.String(length=16), nullable=True),
    sa.Column('evidence_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_file_id'], ['project_files.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicability_conditions_project_id'), 'applicability_conditions', ['project_id'], unique=False)
    op.create_table('parsed_workscope_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_file_id', sa.Integer(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('sheet_index', sa.Integer(), nullable=True),
    sa.Column('task_ref_raw', sa.String(length=256), nullable=True),
    sa.Column('service_check_raw', sa.String(length=256), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('reference_raw', sa.String(length=512), nullable=True),
    sa.Column('raw_row_json', sa.JSON(), nullable=True),
    sa.Column('row_type', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_file_id'], ['project_files.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_workscope_rows_project_id'), 'parsed_workscope_rows', ['project_id'], unique=False)
    op.create_table('workscope_match_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parsed_row_id', sa.Integer(), nullable=False),
    sa.Column('mpd_task_id', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mpd_task_id'], ['mpd_tasks.id'], ),
    sa.ForeignKeyConstraint(['parsed_row_id'], ['parsed_workscope_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workscope_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('parsed_row_id', sa.Integer(), nullable=False),
    sa.Column('mpd_task_id', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('applicability_status', sa.String(length=16), nullable=False),
    sa.Column('applicability_reason', sa.String(length=512), nullable=True),
    sa.Column('applicability_raw', sa.Text(), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mpd_task_id'], ['mpd_tasks.id'], ),
    sa.ForeignKeyConstraint(['parsed_row_id'], ['parsed_workscope_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workscope_matches_project_id'), 'workscope_matches', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workscope_matches_project_id'), table_name='workscope_matches')
    op.drop_table('workscope_matches')
    op.drop_table('workscope_match_candidates')
    op.drop_index(op.f('ix_parsed_workscope_rows_project_id'), table_name='parsed_workscope_rows')
    op.drop_table('parsed_workscope_rows')
    op.drop_index(op.f('ix_applicability_conditions_project_id'), table_name='applicability_conditions')
    op.drop_table('applicability_conditions')
    op.drop_index(op.f('ix_project_reports_project_id'), table_name='project_reports')
    op.drop_table('project_reports')
    op.drop_index(op.f('ix_project_files_project_id'), table_name='project_files')
    op.drop_table('project_files')
    op.drop_index(op.f('ix_project_condition_answers_project_id'), table_name='project_condition_answers')
    op.drop_table('project_condition_answers')
    op.drop_index(op.f('ix_project_checks_project_id'), table_name='project_checks')
    op.drop_table('project_checks')
    op.drop_index(op.f('ix_modification_evidence_files_project_id'), table_name='modification_evidence_files')
    op.drop_table('modification_evidence_files')
    op.drop_index(op.f('ix_projects_msn'), table_name='projects')
    op.drop_index(op.f('ix_projects_mpd_dataset_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_mpd_tasks_task_reference'), table_name='mpd_tasks')
    op.drop_index(op.f('ix_mpd_tasks_task_number'), table_name='mpd_tasks')
    op.drop_index(op.f('ix_mpd_tasks_task_code'), table_name='mpd_tasks')
    op.drop_index(op.f('ix_mpd_tasks_dataset_id'), table_name='mpd_tasks')
    op.drop_table('mpd_tasks')
    op.drop_index(op.f('ix_mpd_datasets_revision'), table_name='mpd_datasets')
    op.drop_index(op.f('ix_mpd_datasets_model'), table_name='mpd_datasets')
    op.drop_index(op.f('ix_mpd_datasets_manufacturer'), table_name='mpd_datasets')
    op.drop_table('mpd_datasets')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
